POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "testtim",
    "favoritePlants": "testmushroom"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/15

###

PUT http://localhost:3000/users/15
Content-Type: application/json

{
    "username": "updatetest",
    "favoritePlants": "testupdate"
}

###

DELETE http://localhost:3000/users/15